config/routes.rb
ComicRealm::Application.routes.draw do
  resources :documents

  resources :notebooks

	resources :projects
	resources :users

	root 'home#index'

	post 'login' => 'sessions#create', :as => 'login'
	get 'logout' => 'sessions#destroy', :as => 'logout'
	get 'signup' => 'users#new', :as => 'signup'
	post 'signup' => 'users#create'

	get 'profile/:username' => 'users#view'
	get 'profile/edit' => 'users#edit'

	get 'home' => 'home#home', :as => 'home'

	get 'test/text-editor' => 'test#text_editor'

end

app/models/notebook.rb
class Notebook < ActiveRecord::Base
	belongs_to :project
	belongs_to :owner, :class_name => 'User'

	has_many :documents

	validate :title, presence: true, uniqueness: true
	validate :description, presence: true
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
  before_action :set_notebook, only: [:show, :edit, :update, :destroy]

  # GET /notebooks
  # GET /notebooks.json
  def index
    @notebooks = Notebook.all
  end

  # GET /notebooks/1
  # GET /notebooks/1.json
  def show
  end

  # GET /notebooks/new
  def new
    @notebook = Notebook.new
  end

  # GET /notebooks/1/edit
  def edit
  end

  # POST /notebooks
  # POST /notebooks.json
  def create
    @notebook = Notebook.new(notebook_params)

    respond_to do |format|
      if @notebook.save
        format.html { redirect_to @notebook, notice: 'Notebook was successfully created.' }
        format.json { render action: 'show', status: :created, location: @notebook }
      else
        format.html { render action: 'new' }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notebooks/1
  # PATCH/PUT /notebooks/1.json
  def update
    respond_to do |format|
      if @notebook.update(notebook_params)
        format.html { redirect_to @notebook, notice: 'Notebook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notebooks/1
  # DELETE /notebooks/1.json
  def destroy
    @notebook.destroy
    respond_to do |format|
      format.html { redirect_to notebooks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notebook
      @notebook = Notebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notebook_params
      params.require(:notebook).permit(:project_id, :title, :description)
    end
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/notebooks/_form.html.erb
<%= form_for(@notebook) do |f| %>
  <% if @notebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notebook.errors.count, "error") %> prohibited this notebook from being saved:</h2>

      <ul>
      <% @notebook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notebooks/edit.html.erb
<h1>Editing notebook</h1>

<%= render 'form' %>

<%= link_to 'Show', @notebook %> |
<%= link_to 'Back', notebooks_path %>

app/views/notebooks/index.html.erb
<h1>Listing notebooks</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notebooks.each do |notebook| %>
      <tr>
        <td><%= notebook.project_id %></td>
        <td><%= notebook.title %></td>
        <td><%= notebook.description %></td>
        <td><%= link_to 'Show', notebook %></td>
        <td><%= link_to 'Edit', edit_notebook_path(notebook) %></td>
        <td><%= link_to 'Destroy', notebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notebook', new_notebook_path %>

app/views/notebooks/new.html.erb
<h1>New notebook</h1>

<%= render 'form' %>

<%= link_to 'Back', notebooks_path %>

app/views/notebooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @notebook.project_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @notebook.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @notebook.description %>
</p>

<%= link_to 'Edit', edit_notebook_path(@notebook) %> |
<%= link_to 'Back', notebooks_path %>